namespace NexHUD.elite
{
    public enum EliteState
    {
        Unknow,
        Blight,
        Boom,
        Bust,
        CivilLiberty,
        CivilUnrest,
        CivilWar,
        ColdWar,
        Colonisation,
        Damaged,
        Drought,
        Election,
        Expansion,
        Famine,
        HistoricEvent,
        InfrastructureFailure,
        Investment,
        Lockdown,
        NaturalDisaster,
        None,
        Outbreak,
        PirateAttack,
        PublicHoliday,
        Retreat,
        Revolution,
        TechnologicalLeap,
        TerroristAttack,
        TradeWar,
        UnderRepairs,
        War
    }
}
