using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NexHUD.EDEngineer
{
    public enum BlueprintType
    {
        PlasmaAccelerator,
        ElectronicCountermeasure,
        LifeSupport,
        HullReinforcementPackage,
        Cannon,
        Thrusters,
        Multi_cannon,
        MissileRack,
        PowerPlant,
        ChaffLauncher,
        FrameShiftDriveInterdictor,
        ShieldGenerator,
        PointDefence,
        ShieldBooster,
        KillWarrantScanner,
        RailGun,
        PowerDistributor,
        FragmentCannon,
        MineLauncher,
        BeamLaser,
        Armour,
        ProspectorLimpetController,
        ManifestScanner,
        BurstLaser,
        HeatSinkLauncher,
        WakeScanner,
        PulseLaser,
        Refinery,
        AutoField_MaintenanceUnit,
        FuelTransferLimpetController,
        FrameShiftDrive,
        HatchBreakerLimpetController,
        FuelScoop,
        TorpedoPylon,
        CollectorLimpetController,
        ShieldCellBank,
        GuardianPlasmaChargerMunitions,
        GuardianGaussCannonMunitions,
        AXSmallCalibreMunitions,
        AXRemoteFlakMunitions,
        EnzymeMissileLauncherMunitions,
        FlechetteLauncherMunitions,
        GuardianShardCannonMunitions,
        AXExplosiveMunitions,
        Limpets,
        FSDInjection,
        PlasmaMunitions,
        ExplosiveMunitions,
        SmallCalibreMunitions,
        HighVelocityMunitions,
        LargeCalibreMunitions,
        AFMRefill,
        SRVAmmoRestock,
        SRVRepair,
        SRVRefuel,
        Sensors,
        SurfaceScanner,
        Unlock,
        Human,
        Guardian,
    }
}
